// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onkmssciuonxlticpiey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ua21zc2NpdW9ueGx0aWNwaWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODkwMjAsImV4cCI6MjA3MTk2NTAyMH0.2BEp_uuqThmDNWj-E73iG25N4cAweUEfrzcZv_ovkAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});